### ISSUE TITLE
Reverted changes at move_base_dwa.launch

### ISSUE THREAD

**Issue by MFernandezCarmona** [LCAS/iliad#22]
Hi,
@tejaspp, I noticed you added some extra stuff at `iliad/nav_simulation/launch/move_base_dwa.launch` that I removed. (A fake goal publisher, laser filters) I had to do that because they were conflicting with other launchfiles that where calling them. 
Check it out, because most likely I have broken some of your scripts.

**Comment by tejaspp** [comment]
In LCAS/iliad/nav_simulation/launch/move_base_dwa.launch, you will have to end group ns="$(arg prefix)" with /group at the end. You will also have to add 

arg name="map_frame" default="map_laser2d"/
arg name="base_frame" default="$(arg prefix)/base_link"/

This is because in lines 36, 67 and 68, it needs to know what is "$(arg map_frame)" and "$(arg base_frame)".
